# Generated by Django 4.0.6 on 2022-09-17 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('updated', models.DateField()),
                ('schedule_plan', models.DateField()),
                ('vote_star', models.IntegerField(null=True)),
                ('vote_percent', models.IntegerField(null=True)),
                ('vote_status', models.CharField(max_length=10000, null=True)),
            ],
            options={
                'db_table': 'company_backup',
            },
        ),
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=10000, null=True)),
                ('telephone', models.CharField(max_length=10000)),
                ('address', models.CharField(max_length=10000, null=True)),
                ('district', models.CharField(max_length=150)),
                ('sub_district', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('approve_user', models.CharField(max_length=10000, null=True)),
                ('update_by', models.DateField()),
                ('schedule_plan', models.DateField()),
                ('vote_star', models.IntegerField(null=True)),
                ('vote_percent', models.IntegerField(null=True)),
                ('vote_status', models.CharField(max_length=10000, null=True)),
                ('updated', models.DateField(default=datetime.datetime.now)),
                ('expired1', models.BooleanField(default=False)),
                ('expired2', models.BooleanField(default=False)),
                ('expired3', models.BooleanField(default=False)),
                ('expired4', models.BooleanField(default=False)),
                ('expired5', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'company_profile',
                'ordering': ('userid',),
            },
        ),
        migrations.CreateModel(
            name='company_qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
            options={
                'db_table': 'company_qrcode',
            },
        ),
        migrations.CreateModel(
            name='thai_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('district', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'thai_district',
            },
        ),
        migrations.CreateModel(
            name='thai_postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('postcode', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'thai_postcode',
            },
        ),
        migrations.CreateModel(
            name='thai_province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'thai_province',
            },
        ),
        migrations.CreateModel(
            name='thai_sub_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('sub_district', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'thai_sub_district',
            },
        ),
        migrations.CreateModel(
            name='username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'username',
            },
        ),
    ]
