# Generated by Django 4.1.3 on 2022-12-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('broadcast_on', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-broadcast_on'],
            },
        ),
        migrations.CreateModel(
            name='company_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=10000, null=True)),
                ('job_id', models.CharField(max_length=10000, null=True)),
                ('schedule_plan', models.IntegerField(null=True)),
                ('dual_date', models.DateField()),
                ('vote_star', models.IntegerField(null=True)),
                ('vote_percent', models.IntegerField(null=True)),
                ('vote_status', models.CharField(max_length=10000, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_notice',
            },
        ),
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=10000, null=True)),
                ('telephone', models.CharField(max_length=10000)),
                ('address', models.CharField(max_length=10000, null=True)),
                ('district', models.CharField(max_length=150)),
                ('sub_district', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('job_id', models.CharField(max_length=10000, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('percent_cost', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('approve_user', models.CharField(max_length=10000, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule_plan', models.IntegerField(null=True)),
                ('dual_date', models.DateField()),
                ('vote_star', models.IntegerField(null=True)),
                ('vote_percent', models.IntegerField(null=True)),
                ('vote_status', models.CharField(max_length=10000, null=True)),
                ('qr_type', models.IntegerField(default=1)),
                ('avg_vote', models.FloatField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_profile',
                'ordering': ('userid',),
            },
        ),
        migrations.CreateModel(
            name='company_qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_qrcode',
            },
        ),
        migrations.CreateModel(
            name='username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'username',
            },
        ),
    ]
