# Generated by Django 4.1.3 on 2022-12-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_notice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company_qrcode',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
