# Generated by Django 4.1.3 on 2022-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0002_alter_company_notice_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
