# Generated by Django 4.1.3 on 2022-12-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0003_broadcastnotification_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_profile',
            name='feed',
            field=models.BooleanField(default=True),
        ),
    ]
