# Generated by Django 4.2.11 on 2024-04-06 10:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_home", "0004_company_profile_feed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_qrcode",
            name="qr_code",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="qr_codes"
            ),
        ),
    ]
