# Generated by Django 4.2.11 on 2024-04-06 10:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_home", "0005_alter_company_qrcode_qr_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "qr_code",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "library",
            },
        ),
        migrations.AlterField(
            model_name="company_qrcode",
            name="qr_code",
            field=models.FileField(blank=True, upload_to="qr_codes"),
        ),
    ]
