# Generated by Django 4.2.11 on 2024-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_home", "0006_library_alter_company_qrcode_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="qr_code",
            field=models.FileField(blank=True, upload_to="qr_codes"),
        ),
    ]
