# Generated by Django 4.2.11 on 2024-04-08 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_home", "0008_delete_library_remove_company_profile_dual_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company_notice",
            old_name="dual_date",
            new_name="end_date",
        ),
    ]
